name: frigotehnica
author: Frigotehnica
email: office@frigotehnica.com
url: https://github.com/frxbg/frigotehnica-boss-cloudflare-tunnel
version: '1.3.0'
title: 'Frigotehnica Cloudflare Tunnel'
icon: cloud
dependencies:
    - !PluginDependency {
        plugin_name: core
    }
resources:
    - 'resources/module.js'
    - 'resources/view.html'
    - 'resources/style.css'
    - 'ng:ajenti.frigotehnica'
